### ISSUE TITLE
linenumber for annotations

### ISSUE THREAD

**Issue by nistal97** [Privado-Inc/privado-core#583]
Hi team, just wanna check if it's possible to get linenumber for annotations?
from my test annotations from cpg doesn't has "linenum" or "columnnum" property, as it's optional, could u pls confirm?

`class Annotation(graph: Graph, id: Long)
    extends NodeRef[AnnotationDb](graph, id)
    with AnnotationBase
    with StoredNode
    with Expression {
  override def argumentIndex: scala.Int      = get().argumentIndex
  override def argumentName: Option[String]  = get().argumentName
  override def code: String                  = get().code
  override def columnNumber: Option[Integer] = get().columnNumber
  override def fullName: String              = get().fullName
  override def lineNumber: Option[Integer]   = get().lineNumber`

**Comment by khemrajrathore** [comment]
Hi @nistal97, 
Yes lineNumber and columnNumber are optional, but they are present in most cases. 
Would recommend to add code snippet for which the lineNumber or columnNumber is missing. Can spend some time on it

**Comment by nistal97** [comment]
@khemrajrathore  thanks for the quick resp,  here's my test

source: java
@efg(a="1")
    public static void main(@pqr String[] args, @xyz1 int i) {
}

in privado we print the annotation property map
cpg.typ.iterator.next().annotation.iterator.next()

Mon Jun 05 07:47:40 UTC 2023 - Brewing result...
HashMap(NAME -> efg, ARGUMENT_INDEX -> -1, FULL_NAME -> java.io.efg, _id -> 26, CODE -> @efg(a = "1"), ORDER -> 6, _label -> ANNOTATION)
HashMap(NAME -> pqr, ARGUMENT_INDEX -> -1, FULL_NAME -> java.io.pqr, _id -> 20, CODE -> @pqr, ORDER -> 1, _label -> ANNOTATION)
HashMap(NAME -> xyz1, ARGUMENT_INDEX -> -1, FULL_NAME -> java.io.xyz1, _id -> 22, CODE -> @xyz1, ORDER -> 1, _label -> ANNOTATION)

so the properties contain NAME, FULL_NAME, id, CODE, but no linenum/columnnum

**Comment by khemrajrathore** [comment]
Hi @nistal97 I tried with the sample code

```
class abc {
    @efg(a="1")
    public static void main(@pqr String[] args, @xyz1 int i) {
    }
}
``` 

I am able to get line number and columnNumber for all annotations. I used the query 
`cpg.annotation.map(_.propertiesMap()).foreach(println)`

Alternatively the linenumber for annotation can be accessed using `cpg.annotation.lineNumber`

**Comment by nistal97** [comment]
this is interesting, it's not showing line and column in my local, btw i am customizing based on version pulled in 2023.Jan, not sure if this got fixed recently. Thanks and let me try the latest

**Comment by khemrajrathore** [comment]
Marking this closed
